apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: prod.devtrails.co.nz
    http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-service
          servicePort: 8080